### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Glideh** [bhrutledge/dockerfiles#1]
Nice light image (the only one I found based on Alpine).
Getting this warning though:

```
$ docker run --rm -v $PWD:/src -w /src bhrutledge/compass watch
```

> DEPRECATION WARNING on line 87 of /usr/lib/ruby/gems/2.3.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_deprecated-support.scss: #{} interpolation near operators will be simplified

**Comment by bhrutledge** [comment]
Thanks! Since Compass doesn't seem to be maintained, I'm guessing the solution is to install a specific version of Ruby. However, Docker isn't part of my workflow right now, so diving into this isn't really a priority. But feel free to fork. :)

**Comment by Glideh** [comment]
I see.
I didn't know Compass was not maintained anymore :(
Anyway it's printing the warning only for the first run.
Your image did the trick for me (I just needed it on an existing project with a `config.rb` all prepared).
